---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "efk.fullname" . }}
  labels:
    app: {{ template "efk.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: elasticsearch.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: efk-elasticsearch
          servicePort: 9200
  - host: kibana.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: efk-kibana
          servicePort: 443
