---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "elasticsearch.fullname" . }}-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
