---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    k8s-app: elasticsearch
    #version: v5.6.4
    version: 6.2.4
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: {{ template "elasticsearch.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: 6.2.4
      #version: v5.6.4
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: 6.2.4
        #version: v5.6.4
        kubernetes.io/cluster-service: "true"
    spec:
      #nodeSelector:
      #  elastichost: "true"
      containers:
      #- image: k8s.gcr.io/elasticsearch:v5.6.4
      - name: {{ template "elasticsearch.fullname" . }}
        #image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        image: launcher.gcr.io/google/elasticsearch6:latest
        #args: ["/bin/sleep", "100"]
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: {{ template "elasticsearch.fullname" . }}-pvc-volume
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: MINIMUM_MASTER_NODES
          value: "1"
        - name: cluster.name
          value: "otus-cluster"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: {{ template "elasticsearch.fullname" . }}-pvc-volume
        persistentVolumeClaim:
          claimName: {{ template "elasticsearch.fullname" . }}-claim
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: {{ template "elasticsearch.fullname" . }}-init
        securityContext:
          privileged: true
