---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "cicd.fullname" . }}
  labels:
    app: {{ template "cicd.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: chartmuseum.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab-chartmuseum
          servicePort: 8080

