---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "proxy.fullname" . }}
  labels:
    app: {{ template "proxy.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: elasticsearch.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: efk-elasticsearch
          servicePort: 9200
  - host: kibana.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: efk-kibana
          servicePort: 443
  - host: prometheus.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-prometheus-server
          servicePort: 80
  - host: alertmanager.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-prometheus-alertmanager
          servicePort: 80
