dependencies:
  - name: gitlab-omnibus
    version: 0.1.37
    repository: https://charts.gitlab.io
  - name: chartmuseum
    version: 1.3.1
    repository: https://kubernetes-charts.storage.googleapis.com
