gitlab-omnibus:
  baseDomain: cicd.andywow.xyz
  legoEmail: 1andreysusoev@gmail.com
  baseIP: 35.195.84.99
  gitlabCEImage: gitlab/gitlab-ce:10.6.4-ce.0
  gitlab-runner:
    runners:
      privileged: true
